(dp1
S'output'
p2
S"<type 'exceptions.ValueError'> invalid literal for int() with base 10: '192.168.0.108'"
p3
sS'layer'
p4
S'/home/camilo/Escritorio/repo_git/web2py/applications/datos/controllers/maquinas.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n# intente algo como\ndef index():\n    cabezas = ["ip_machine", "code_course", "operative_system", "memory", "processor"]\n    filas =  db1((db1.machine.ip_machine)).select(\n        db1.machine.ip_machine, db1.machine.code_course, db1.machine.operative_system,db1.machine.memory,db1.machine.processor\n    )\n    acciones = [T("Restart"),T("Add user")]\n    return locals()\n\ndef ejecutar():\n    formulario = response.vars.maquinas\n    print "formulario es ", formulario\n    response.flash=T(\'this text should appear!\')\n    redirect(URL(\'maquinas\', \'index\'))\n    \ndef mostrar():\n    #campos = [\'ip_machine\', \'code_course\',\'operative_system\',\'memory\',\'processor\']\n    grid = SQLFORM.grid(db1.machine, field_id=db1.machine.ip_machine,\n                        selectable = lambda ids : vars.maquinas.append(dict(id=ids))\n                       #selectable = lambda ids : redirect(URL(\'maquinas\', \'ejecutar\', vars=dict(id=ids)))\n                       )\n    return locals()\n\nresponse._vars=response._caller(mostrar)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/camilo/Escritorio/repo_git/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/camilo/Escritorio/repo_git/web2py/applications/datos/controllers/maquinas.py", line 25, in <module>\n  File "/home/camilo/Escritorio/repo_git/web2py/gluon/globals.py", line 415, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/camilo/Escritorio/repo_git/web2py/applications/datos/controllers/maquinas.py", line 20, in mostrar\n    selectable = lambda ids : vars.maquinas.append(dict(id=ids))\n  File "/home/camilo/Escritorio/repo_git/web2py/gluon/sqlhtml.py", line 2862, in grid\n    records = [int(r) for r in htmltable.vars.records]\nValueError: invalid literal for int() with base 10: \'192.168.0.108\'\n'
p11
s.