(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'df' is not defined"
p3
sS'layer'
p4
S'/home/camilo/Escritorio/repo_git/web2py/applications/datos/controllers/maquinas.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n# intente algo como\ndef index():\n    cabezas = ["ip_machine", "code_course", "operative_system", "memory", "processor"]\n    test =  db1((db1.machine.ip_machine)).select(\n        db1.machine.ip_machine, db1.machine.code_course, db1.machine.operative_system,db1.machine.memory,db1.machine.processor\n    )\n    \n    temp=[]\n\n    for row in df.iterrows():\n        index, data = row\n        emp.append(data.tolist())\n    \n    \n    \n    print "Busqueda"\n    print temp\n    filas = db1(db1.machine).select()\n    return dict(cabezas=cabezas)\n\nresponse._vars=response._caller(index)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/camilo/Escritorio/repo_git/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/camilo/Escritorio/repo_git/web2py/applications/datos/controllers/maquinas.py", line 22, in <module>\n  File "/home/camilo/Escritorio/repo_git/web2py/gluon/globals.py", line 415, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/camilo/Escritorio/repo_git/web2py/applications/datos/controllers/maquinas.py", line 11, in index\n    for row in df.iterrows():\nNameError: global name \'df\' is not defined\n'
p11
s.